version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::179805212275:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-CGWXF2KW93QN"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::179805212275:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-4TS3AVZ95SHR"
cloudformation_execution_role = "arn:aws:iam::179805212275:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-IKGZDYFIQJ9X"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-98493jjs9rjk"
image_repository = ""
region = "ap-south-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::179805212275:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-PVRK3WON6EPY"
cloudformation_execution_role = "arn:aws:iam::179805212275:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-16ZT92J2VHFM1"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1tvwo2szpy1kz"
image_repository = ""
region = "ap-south-1"
